## cleaning for CIS4400
- EDA & data cleanup to import into database for visualization

In [22]:
#importing standard modules
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

anc = 'TsaThroughput.ANC.csv'

#creating function to look at individual files
df_anc = pd.read_csv(anc)
df_anc['ANC International'] = df_anc['ANC International'].fillna(0)
anc_c1 = df_anc['ANC International'] != 0
df_anc[anc_c1]

             Date      Hour  ANC International  ANC South Checkpoint
1333   2019-02-23  15:00:00              151.0                 215.0
1334   2019-02-23  16:00:00              123.0                 292.0
3967   2019-06-13  14:00:00               37.0                 405.0
3968   2019-06-13  15:00:00               73.0                 196.0
4301   2019-06-27  13:00:00               45.0                 814.0
...           ...       ...                ...                   ...
31938  2022-09-01  14:00:00               57.0                 535.0
31939  2022-09-01  15:00:00               63.0                 225.0
31940  2022-09-01  16:00:00                5.0                 347.0
32107  2022-09-08  15:00:00               90.0                 285.0
32108  2022-09-08  16:00:00               47.0                 210.0

[97 rows x 4 columns]

In [ ]:
#all file
tot = 'TsaThroughput.All.csv'

df_tot = pd.read_csv(tot)
df_tot

,Date,Hour,ABE ABE Main Terminal,ABI ABIA,ABQ Checkpoint for A/B Gates,ABR Gate,ABY ABY-A,ACK Main Terminal - 1,ACT ACTA,ACV ACV01,...,VPS VPS-A,VPS VPS-C,VRB Checkpoint 1,WRG WRG-01,WYS WYSZ,XNA Checkpoint 2,XWA Main Checkpoint,YAK YAK-01,YKM YKM Main,YNG Gate
0,2018-12-30,00:00:00,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-12-30,01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-12-30,02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-12-30,03:00:00,NaN,NaN,134.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.0,NaN
4,2018-12-30,04:00:00,146.0,35.0,598.0,54.0,NaN,NaN,30.0,6.0,...,120.0,NaN,NaN,NaN,NaN,108.0,NaN,NaN,39.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32563,2022-09-17,19:00:00,NaN,NaN,7.0,NaN,NaN,40.0,NaN,44.0,...,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN
32564,2022-09-17,20:00:00,NaN,NaN,15.0,NaN,NaN,NaN,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32565,2022-09-17,21:00:00,NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32566,2022-09-17,22:00:00,NaN,NaN,69.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32567,2022-09-17,23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 748 columns of nope